Feature/implement streaming capabilities
Fr0ntierX/polaris-proxy pull request #8
Opened 2024-12-04 11:26 UTC by codificativ

2024-12-09 10:46 UTC, haltakov requested changes

2024-12-09 10:46 UTC, haltakov commented on src/proxy/handlers/axiosProxyHandler.ts
> +export class DecryptStream extends Transform {
Why not use this one from the Polaris SDK? Seems like duplicated code?

2024-12-09 10:46 UTC, haltakov commented on src/proxy/handlers/axiosProxyHandler.ts
> +export function axiosProxyResponseInterceptor(sdk: PolarisSDK): (response: AxiosResponse) => Promise<AxiosResponse> {
This also seems like something that should be in the Polaris SDK, no?

2024-12-09 10:46 UTC, haltakov commented on src/proxy/handlers/axiosProxyHandler.ts
> +      const responseInterceptor = this.axiosInstance.interceptors.response.use((response: AxiosResponse) => {
This also seems like soemthing we could have from the Polaris SDK

2024-12-09 10:46 UTC, haltakov commented on src/proxy/handlers/polarisProxyHandler.ts
> +class EncryptStream extends Transform {
Polaris SDK?

2024-12-13 13:10 UTC, haltakov commented
https://app.shortcut.com/fr0ntierx/story/8489/b-implement-streaming-capabilities-in-the-polaris-proxy-and-polaris-sdk

2025-01-14 09:56 UTC, haltakov requested changes
There are also some issues in the automated checks in the CI. I recommend running yarn check locally before pushing to make sure prettier and lint rules are satisfied

2025-01-14 09:56 UTC, haltakov commented on src/config/index.ts
> +  const polarisResponseWrappedKeyHeader = process.env.POLARIS_CONTAINER_HEADER_KEY || "polaris-response-wrapped-key";
We need a different env var name here ;)

2025-01-14 09:56 UTC, haltakov commented on src/proxy/index.ts
> +import { PolarisProxyHandler } from "./handlers/PolarisProxyHandler";
Not sure this change is needed. The file starts with a lowercase letter

2025-01-14 09:56 UTC, haltakov commented on src/proxy/types/index.ts
> +    body?: any;
Can't the body stay `Buffer`?

2025-01-16 22:15 UTC, codificativ commented on src/proxy/handlers/axiosProxyHandler.ts
> +      const responseInterceptor = this.axiosInstance.interceptors.response.use((response: AxiosResponse) => {
this file no more existing

2025-01-16 22:15 UTC, codificativ commented on src/proxy/handlers/polarisProxyHandler.ts
> +class EncryptStream extends Transform {
yep done

2025-01-16 22:16 UTC, codificativ commented on src/config/index.ts
> +  const polarisResponseWrappedKeyHeader = process.env.POLARIS_CONTAINER_HEADER_KEY || "polaris-response-wrapped-key";
outch okay `POLARIS_CONTAINER_WRAPPED_HEADER_KEY`

2025-01-16 22:21 UTC, codificativ commented on src/proxy/types/index.ts
> +    body?: any;
When it's a stream I guess, but yes that's no more used as we're treating in-between all as chunks stream based between the interceptors (when it's a buffer - implicitly treater as a stream of one chunk)

2025-01-16 22:21 UTC, codificativ commented on src/proxy/index.ts
> +import { PolarisProxyHandler } from "./handlers/PolarisProxyHandler";
the weird thing got in IDE syntax renaming suggestion, but on mac that's Upper case i'm not sure 
<img width="373" alt="image" src="https://github.com/user-attachments/assets/7f2e943e-cac8-491c-9f6f-fd61f85bbf9d" />

2025-02-14 10:05 UTC, haltakov approved these changes

2025-02-14 10:05 UTC, merged